// The expression list, animation timelines and their order are identical
// across every bible-strong avatar export — only the body shape, colors and
// per-expression eye geometry differ. Shared here to avoid repetition.
import type { Animation } from './freddyAvatar';

export const sharedExpressionOrder = ['neutral', 'upward-side-glance', 'downward-gaze', 'skeptical-right', 'small-attentive', 'wide-downward-gaze', 'surprised-left', 'sleepy-squint', 'angry-right', 'curious-left', 'asymmetric-down-right', 'attentive-left', 'joyful-wide', 'eyes-closed', 'joyful-down-right', 'skeptical-left', 'far-right-glance', 'angry-left', 'playful-right', 'asymmetric-up-left', 'gentle-downward-gaze', 'wide-down-left', 'surprised-wide-left', 'drowsy-closed', 'suspicious-right', 'shy-downward', 'angry-brows', 'uneasy-left'];

export const sharedAnimationOrder = ['sleeping', 'waking', 'idle', 'listening', 'thinking', 'searching', 'working', 'excited', 'bored', 'suspicious', 'angry', 'drowsy', 'happy', 'curious', 'confused', 'surprised', 'proud', 'shy', 'sad', 'laughing', 'scared', 'playful', 'celebrate'];

export const sharedAnimations: Record<string, Animation> = {
  sleeping: { playbackMode: 'loop', steps: [{ expression: 'eyes-closed', holdMs: 3600, transitionMs: 500, transition: 'smooth' }, { expression: 'drowsy-closed', holdMs: 3600, transitionMs: 500, transition: 'smooth' }, { expression: 'sleepy-squint', holdMs: 3600, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 4800, minIntervalMs: 6500, maxIntervalMs: 9500, durationMs: 420 }, metadata: { label: 'sleeping', description: '', group: 'Cycle de vie' } },
  waking: { playbackMode: 'loop', steps: [{ expression: 'eyes-closed', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 1200, minIntervalMs: 1800, maxIntervalMs: 3600, durationMs: 220 }, metadata: { label: 'waking', description: '', group: 'Cycle de vie' } },
  idle: { playbackMode: 'loop', steps: [{ expression: 'upward-side-glance', holdMs: 5200, transitionMs: 500, transition: 'smooth' }, { expression: 'curious-left', holdMs: 5200, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2600, minIntervalMs: 3400, maxIntervalMs: 6200, durationMs: 280 }, metadata: { label: 'idle', description: '', group: 'Cycle de vie' } },
  listening: { playbackMode: 'loop', steps: [{ expression: 'attentive-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'downward-gaze', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'gentle-downward-gaze', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 3200, minIntervalMs: 4800, maxIntervalMs: 7200, durationMs: 240 }, metadata: { label: 'listening', description: '', group: 'Cycle de vie' } },
  thinking: { playbackMode: 'loop', steps: [{ expression: 'curious-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'angry-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'skeptical-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'playful-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'skeptical-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'thinking', description: '', group: 'Cycle de vie' } },
  searching: { playbackMode: 'loop', steps: [{ expression: 'far-right-glance', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'asymmetric-down-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'surprised-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'wide-down-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'wide-downward-gaze', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'asymmetric-up-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'searching', description: '', group: 'Cycle de vie' } },
  working: { playbackMode: 'loop', steps: [{ expression: 'angry-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'angry-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'joyful-wide', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'attentive-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'working', description: '', group: 'Cycle de vie' } },
  excited: { playbackMode: 'loop', steps: [{ expression: 'joyful-down-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'playful-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'surprised-wide-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'surprised-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'joyful-wide', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 1200, minIntervalMs: 1800, maxIntervalMs: 3600, durationMs: 220 }, metadata: { label: 'excited', description: '', group: 'Réactions' } },
  bored: { playbackMode: 'loop', steps: [{ expression: 'sleepy-squint', holdMs: 3600, transitionMs: 500, transition: 'smooth' }, { expression: 'drowsy-closed', holdMs: 3600, transitionMs: 500, transition: 'smooth' }, { expression: 'upward-side-glance', holdMs: 3600, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 4800, minIntervalMs: 6500, maxIntervalMs: 9500, durationMs: 420 }, metadata: { label: 'bored', description: '', group: 'Réactions' } },
  suspicious: { playbackMode: 'loop', steps: [{ expression: 'skeptical-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'skeptical-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'suspicious-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'suspicious', description: '', group: 'Réactions' } },
  angry: { playbackMode: 'loop', steps: [{ expression: 'angry-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'angry-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'angry', description: '', group: 'Réactions' } },
  drowsy: { playbackMode: 'loop', steps: [{ expression: 'sleepy-squint', holdMs: 3600, transitionMs: 500, transition: 'smooth' }, { expression: 'drowsy-closed', holdMs: 3600, transitionMs: 500, transition: 'smooth' }, { expression: 'eyes-closed', holdMs: 3600, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 4800, minIntervalMs: 6500, maxIntervalMs: 9500, durationMs: 420 }, metadata: { label: 'drowsy', description: '', group: 'Réactions' } },
  happy: { playbackMode: 'loop', steps: [{ expression: 'joyful-down-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'joyful-wide', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'playful-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'gentle-downward-gaze', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'happy', description: '', group: 'Réactions' } },
  curious: { playbackMode: 'loop', steps: [{ expression: 'surprised-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'surprised-wide-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'upward-side-glance', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'far-right-glance', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'curious', description: '', group: 'Réactions' } },
  confused: { playbackMode: 'loop', steps: [{ expression: 'skeptical-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'skeptical-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'curious-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'confused', description: '', group: 'Réactions' } },
  surprised: { playbackMode: 'loop', steps: [{ expression: 'surprised-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'surprised-wide-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 1200, minIntervalMs: 1800, maxIntervalMs: 3600, durationMs: 220 }, metadata: { label: 'surprised', description: '', group: 'Réactions' } },
  proud: { playbackMode: 'loop', steps: [{ expression: 'far-right-glance', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'curious-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'joyful-down-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'proud', description: '', group: 'Réactions' } },
  shy: { playbackMode: 'loop', steps: [{ expression: 'upward-side-glance', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'shy-downward', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'eyes-closed', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'shy', description: '', group: 'Réactions' } },
  sad: { playbackMode: 'loop', steps: [{ expression: 'sleepy-squint', holdMs: 3600, transitionMs: 500, transition: 'smooth' }, { expression: 'eyes-closed', holdMs: 3600, transitionMs: 500, transition: 'smooth' }, { expression: 'drowsy-closed', holdMs: 3600, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 4800, minIntervalMs: 6500, maxIntervalMs: 9500, durationMs: 420 }, metadata: { label: 'sad', description: '', group: 'Réactions' } },
  laughing: { playbackMode: 'loop', steps: [{ expression: 'joyful-down-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'joyful-wide', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'playful-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 1200, minIntervalMs: 1800, maxIntervalMs: 3600, durationMs: 220 }, metadata: { label: 'laughing', description: '', group: 'Réactions' } },
  scared: { playbackMode: 'loop', steps: [{ expression: 'surprised-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'surprised-wide-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 1200, minIntervalMs: 1800, maxIntervalMs: 3600, durationMs: 220 }, metadata: { label: 'scared', description: '', group: 'Réactions' } },
  playful: { playbackMode: 'loop', steps: [{ expression: 'joyful-down-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'playful-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'joyful-wide', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'curious-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 2100, minIntervalMs: 2800, maxIntervalMs: 5000, durationMs: 260 }, metadata: { label: 'playful', description: '', group: 'Réactions' } },
  celebrate: { playbackMode: 'loop', steps: [{ expression: 'joyful-down-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'curious-left', holdMs: 2300, transitionMs: 500, transition: 'smooth' }, { expression: 'playful-right', holdMs: 2300, transitionMs: 500, transition: 'smooth' }], blink: { enabled: true, initialDelayMs: 1200, minIntervalMs: 1800, maxIntervalMs: 3600, durationMs: 220 }, metadata: { label: 'celebrate', description: '', group: 'Réactions' } },
};
